### Подключаем пакет

In [2]:
import numpy as np
import pandas as pd
from IPython.display import display

## Аэропорты
### Загрузка данных

In [3]:
airports = pd.read_csv('datasets/airports.csv')
airports.head()

,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081689834590001,145.391998291,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
0,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
1,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
2,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports
3,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports
4,6,Wewak International Airport,Wewak,Papua New Guinea,WWK,AYWK,-3.583830,143.669006,19,10,U,Pacific/Port_Moresby,airport,OurAirports

In [4]:
columns = ['Airport ID', 'Name', 'City', 'Country', 'IATA', 
           'ICAO', 'Latitude', 'Longitude', 'Altitude', 'Timezone', 
           'DST', 'Tz database', 'Type', 'Source']
airports = pd.read_csv('datasets/airports.csv', 
                       names = columns)
airports.head()

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database,Type,Source
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports

In [5]:
airports.count()

Airport ID     7184
Name           7184
City           7140
Country        7184
IATA           7182
ICAO           7184
Latitude       7184
Longitude      7184
Altitude       7184
Timezone       7184
DST            7184
Tz database    7184
Type           7184
Source         7184
dtype: int64

In [6]:
airports.City.unique()

array(['Goroka', 'Madang', 'Mount Hagen', ..., 'Wuhu', 'Shanshan',
       'Yingkou'], dtype=object)

In [7]:
airports[airports.IATA.str.len()<3]

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database,Type,Source
56,57,Forestville Airport,Forestville,Canada,\N,CYFE,48.746101,-69.097198,293,-5,A,America/Toronto,airport,OurAirports
103,104,Pitt Meadows Airport,Pitt Meadows,Canada,\N,CYPK,49.216099,-122.709999,11,-8,A,America/Vancouver,airport,OurAirports
205,207,Blida Airport,Blida,Algeria,\N,DAAB,36.503601,2.814170,535,1,N,Africa/Algiers,airport,OurAirports
206,208,Bou Saada Airport,Bou Saada,Algeria,\N,DAAD,35.332500,4.206390,1506,1,N,Africa/Algiers,airport,OurAirports
211,213,Reggane Airport,Reggan,Algeria,\N,DAAN,26.710100,0.285647,955,1,N,Africa/Algiers,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7134,12008,Lebyazhye Air Base,Kamyshin,Russia,\N,XRWL,50.201698,45.208302,381,\N,\N,\N,airport,OurAirports
7135,12009,Smolensk North Airport,Smolensk,Russia,\N,XUBS,54.824000,32.025000,820,\N,\N,\N,airport,OurAirports
7136,12010,Rtishchevo Air Base,Rtishchevo,Russia,\N,XWPR,52.297317,43.724100,673,\N,\N,\N,airport,OurAirports
7175,12049,Sunchon Air Base,Sunchon,North Korea,\N,ZKSC,39.415699,125.894997,141,\N,\N,\N,airport,OurAirports
7183,12057,Shenyang Dongta Airport,Shenyang,China,\N,ZYYY,41.784401,123.496002,0,\N,\N,\N,airport,OurAirports

In [8]:
airports[airports.IATA.str.len()<3]["IATA"].unique()

array(['\\N'], dtype=object)

In [9]:
airports=airports.replace("\\N",np.nan)
airports['Tz database'].unique()

array(['Pacific/Port_Moresby', 'America/Godthab', 'America/Thule',
       'Atlantic/Reykjavik', 'America/Toronto', 'America/Winnipeg',
       'America/Halifax', 'America/St_Johns', 'America/Vancouver',
       'America/Edmonton', 'America/Coral_Harbour',
       'America/Dawson_Creek', 'America/Regina', 'Africa/Algiers',
       'Africa/Porto-Novo', 'Africa/Ouagadougou', 'Africa/Accra',
       'Africa/Abidjan', 'Africa/Lagos', 'Africa/Niamey', 'Africa/Tunis',
       'Africa/Lome', 'Europe/Brussels', 'Europe/Berlin',
       'Europe/Tallinn', 'Europe/Helsinki', 'Europe/Mariehamn',
       'Europe/London', 'Europe/Guernsey', 'Europe/Jersey',
       'Europe/Isle_of_Man', 'Atlantic/Stanley', 'Europe/Amsterdam',
       'Europe/Dublin', 'Europe/Copenhagen', 'Atlantic/Faeroe',
       'Europe/Luxembourg', 'Europe/Oslo', 'Arctic/Longyearbyen',
       'Europe/Warsaw', 'Europe/Stockholm', 'Africa/Johannesburg',
       'Africa/Gaborone', 'Africa/Brazzaville', 'Africa/Mbabane',
       'Africa/Bangui', 'Africa/Malabo', 'Atlantic/St_Helena',
       'Indian/Mauritius', 'Indian/Chagos', 'Africa/Douala',
       'Africa/Lusaka', 'Indian/Comoro', 'Indian/Mayotte',
       'Indian/Reunion', 'Indian/Antananarivo', 'Africa/Luanda',
       'Africa/Libreville', 'Africa/Sao_Tome', 'Africa/Maputo',
       'Indian/Mahe', 'Africa/Ndjamena', 'Africa/Harare',
       'Africa/Blantyre', 'Africa/Maseru', 'Africa/Kinshasa',
       'Africa/Lubumbashi', 'Africa/Kigali', 'Africa/Bamako',
       'Africa/Banjul', 'Atlantic/Canary', 'Europe/Madrid',
       'Africa/Freetown', 'Africa/Bissau', 'Africa/Monrovia',
       'Africa/Casablanca', 'Africa/Dakar', 'Africa/Nouakchott',
       'Africa/Conakry', 'Atlantic/Cape_Verde', 'Africa/Addis_Ababa',
       'Africa/Bujumbura', 'Africa/Mogadishu', 'Africa/Cairo',
       'Africa/Nairobi', 'Africa/Tripoli', 'Africa/Khartoum',
       'Africa/Juba', 'Africa/Dar_es_Salaam', 'Africa/Kampala',
       'Europe/Tirane', 'Europe/Sofia', 'Asia/Nicosia', 'Europe/Zagreb',
       'Europe/Paris', 'America/Miquelon', 'Europe/Athens',
       'Europe/Budapest', 'Europe/Rome', 'Europe/Ljubljana',
       'Europe/Prague', 'Asia/Jerusalem', 'Europe/Malta', 'Europe/Vienna',
       'Europe/Lisbon', 'Atlantic/Azores', 'Europe/Sarajevo',
       'Europe/Bucharest', 'Europe/Zurich', 'Europe/Istanbul',
       'Europe/Chisinau', 'Europe/Skopje', 'Europe/Gibraltar',
       'Europe/Belgrade', 'Europe/Podgorica', 'Europe/Bratislava',
       'America/Grand_Turk', 'America/Santo_Domingo', 'America/Guatemala',
       'America/Tegucigalpa', 'America/Jamaica', 'America/Mexico_City',
       'America/Mazatlan', 'America/Cancun', 'America/Hermosillo',
       'America/Tijuana', 'America/Managua', 'America/Panama',
       'America/Costa_Rica', 'America/El_Salvador',
       'America/Port-au-Prince', 'America/Havana', nan, 'America/Cayman',
       'America/Nassau', 'America/Belize', 'Pacific/Rarotonga',
       'Pacific/Fiji', 'Pacific/Tongatapu', 'Pacific/Tarawa',
       'Pacific/Wallis', 'Pacific/Apia', 'Pacific/Pago_Pago',
       'Pacific/Tahiti', 'Pacific/Gambier', 'Pacific/Marquesas',
       'Pacific/Efate', 'Pacific/Noumea', 'Pacific/Auckland',
       'Pacific/Chatham', 'Antarctica/South_Pole', 'Asia/Kabul',
       'Asia/Bahrain', 'Asia/Riyadh', 'Asia/Tehran', 'Asia/Amman',
       'Asia/Kuwait', 'Asia/Beirut', 'Asia/Dubai', 'Asia/Muscat',
       'Asia/Karachi', 'Asia/Baghdad', 'Asia/Damascus', 'Asia/Qatar',
       'Pacific/Enderbury', 'Pacific/Saipan', 'Pacific/Guam',
       'Pacific/Majuro', 'Pacific/Midway', 'Pacific/Truk',
       'Pacific/Ponape', 'Pacific/Palau', 'Pacific/Kosrae', 'Asia/Taipei',
       'Asia/Tokyo', 'Asia/Seoul', 'Asia/Manila', 'America/Cordoba',
       'America/Buenos_Aires', 'America/Argentina/La_Rioja',
       'America/Argentina/Salta', 'America/Mendoza', 'America/Catamarca',
       'America/Argentina/Tucuman', 'America/Argentina/San_Juan',
       'America/Jujuy', 'America/Argentina/San_Luis',
       'America/Argentina/Rio_Gallegos', 'America/Argentina/Ushuaia',
       'America/Belem', 'America/Sao_Paulo', 'America/Fortaleza',
       'America/Campo_Grande', 'America/Boa_Vista', 'America/Rio_Branco',
       'America/Santiago', 'Pacific/Easter', 'America/Guayaquil',
       'Pacific/Galapagos', 'America/Asuncion', 'America/Bogota',
       'America/La_Paz', 'America/Paramaribo', 'America/Cayenne',
       'America/Lima', 'America/Montevideo', 'America/Caracas',
       'America/Guyana', 'America/Antigua', 'America/Barbados',
       'America/Dominica', 'America/Martinique', 'America/Guadeloupe',
       'America/Grenada', 'America/St_Thomas', 'America/Puerto_Rico',
       'America/St_Kitts', 'America/St_Lucia', 'America/Aruba',
       'America/Curacao', 'America/Anguilla', 'America/Port_of_Spain',
       'America/Tortola', 'America/St_Vincent', 'Asia/Qyzylorda',
       'Asia/Bishkek', 'Asia/Oral', 'Asia/Baku', 'Asia/Yakutsk',
       'Asia/Vladivostok', 'Asia/Anadyr', 'Asia/Srednekolymsk',
       'Asia/Irkutsk', 'Europe/Kiev', 'Europe/Simferopol',
       'Europe/Moscow', 'Europe/Minsk', 'Europe/Kaliningrad',
       'Asia/Krasnoyarsk', 'Asia/Omsk', 'Europe/Samara',
       'Asia/Yekaterinburg', 'Asia/Ashgabat', 'Asia/Dushanbe',
       'Asia/Samarkand', 'Asia/Calcutta', 'Asia/Colombo',
       'Asia/Phnom_Penh', 'Asia/Dhaka', 'Asia/Hong_Kong',
       'Asia/Vientiane', 'Asia/Macau', 'Asia/Katmandu', 'Asia/Thimphu',
       'Indian/Maldives', 'Asia/Bangkok', 'Asia/Saigon', 'Asia/Rangoon',
       'Asia/Makassar', 'Asia/Jayapura', 'Asia/Kuala_Lumpur',
       'Asia/Brunei', 'Asia/Jakarta', 'Asia/Dili', 'Asia/Singapore',
       'Australia/Brisbane', 'Australia/Darwin', 'Australia/Hobart',
       'Australia/Sydney', 'Australia/Melbourne', 'Australia/Adelaide',
       'Australia/Perth', 'Indian/Christmas', 'Pacific/Norfolk',
       'Asia/Shanghai', 'Asia/Pyongyang', 'Asia/Ulaanbaatar',
       'America/Anchorage', 'Pacific/Honolulu', 'America/New_York',
       'America/Los_Angeles', 'America/Chicago', 'America/Denver',
       'America/Phoenix', 'Europe/Riga', 'Europe/Vilnius', 'Asia/Yerevan',
       'Africa/Asmera', 'Asia/Gaza', 'Asia/Tbilisi', 'Asia/Aden',
       'Atlantic/Bermuda', 'Pacific/Guadalcanal', 'Pacific/Nauru',
       'Pacific/Funafuti', 'Africa/Windhoek', 'Africa/Djibouti',
       'America/Montserrat', 'Pacific/Johnston', 'America/Scoresbysund',
       'America/Blanc-Sablon', 'Africa/El_Aaiun', 'Pacific/Niue',
       'America/Adak', 'Australia/Lord_Howe', 'Indian/Cocos', 'Asia/Hovd',
       'Europe/Vaduz'], dtype=object)

In [10]:
# отберем аэропорты Европы
euro_air = airports[airports['Tz database'].str.contains('Europe', na=False)]
euro_air

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database,Type,Source
296,299,Antwerp International Airport (Deurne),Antwerp,Belgium,ANR,EBAW,51.189400,4.460280,39,1,E,Europe/Brussels,airport,OurAirports
297,300,Beauvechain Air Base,Beauvechain,Belgium,NaN,EBBE,50.758598,4.768330,370,1,E,Europe/Brussels,airport,OurAirports
298,301,Kleine Brogel Air Base,Kleine Brogel,Belgium,NaN,EBBL,51.168301,5.470000,200,1,E,Europe/Brussels,airport,OurAirports
299,302,Brussels Airport,Brussels,Belgium,BRU,EBBR,50.901402,4.484440,184,1,E,Europe/Brussels,airport,OurAirports
300,303,Jehonville Air Base,Bertrix,Belgium,NaN,EBBX,49.891701,5.223890,1514,1,E,Europe/Brussels,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6593,9863,Full Sutton Airfield,York,United Kingdom,NaN,EGNU,53.980598,-0.864722,86,0,U,Europe/London,airport,OurAirports
6594,9864,Sherburn-In-Elmet Airfield,Leeds,United Kingdom,NaN,EGCJ,53.788458,-1.216877,26,0,U,Europe/London,airport,OurAirports
6658,10148,Semyazino Airport,Vladimir,Russia,NaN,UUBL,56.126701,40.314999,554,3,N,Europe/Moscow,airport,OurAirports
6663,10156,Yeysk Airport,Eysk,Russia,NaN,URKE,46.680000,38.210000,60,3,N,Europe/Moscow,airport,OurAirports
6714,10952,Magas Airport,Magas,Russia,IGT,URMS,43.322300,45.012600,1165,3,N,Europe/Moscow,airport,OurAirports

In [11]:
euro_air['Country'].unique()

array(['Belgium', 'Germany', 'Estonia', 'Finland', 'United Kingdom',
       'Guernsey', 'Jersey', 'Isle of Man', 'Netherlands', 'Ireland',
       'Denmark', 'Luxembourg', 'Norway', 'Poland', 'Sweden', 'Spain',
       'Albania', 'Bulgaria', 'Cyprus', 'Croatia', 'France', 'Greece',
       'Hungary', 'Italy', 'Slovenia', 'Czech Republic', 'Malta',
       'Austria', 'Portugal', 'Bosnia and Herzegovina', 'Romania',
       'Switzerland', 'Turkey', 'Moldova', 'Macedonia', 'Gibraltar',
       'Serbia', 'Montenegro', 'Slovakia', 'Ukraine', 'Russia', 'Belarus',
       'Latvia', 'Lithuania', 'United States'], dtype=object)

In [12]:
euro_air[euro_air['Country'] == 'United States']

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database,Type,Source
6489,9403,Taszár Air Base,Columbus,United States,TZR,LHTA,46.393101,17.9175,531,1,A,Europe/Budapest,airport,OurAirports

In [13]:
airports[airports['IATA'] == 'TZR']

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database,Type,Source
6489,9403,Taszár Air Base,Columbus,United States,TZR,LHTA,46.393101,17.9175,531,1,A,Europe/Budapest,airport,OurAirports

In [14]:
airports[airports['City'] == 'Columbus']

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database,Type,Source
3459,3674,Rickenbacker International Airport,Columbus,United States,LCK,KLCK,39.813801,-82.927803,744,-5,A,America/New_York,airport,OurAirports
3541,3759,Port Columbus International Airport,Columbus,United States,CMH,KCMH,39.998001,-82.891899,815,-5,A,America/New_York,airport,OurAirports
3984,4255,Columbus Metropolitan Airport,Columbus,United States,CSG,KCSG,32.516300,-84.938904,397,-5,A,America/New_York,airport,OurAirports
5591,7511,Ohio State University Airport,Columbus,United States,OSU,KOSU,40.079800,-83.072998,905,-5,U,America/New_York,airport,OurAirports
6489,9403,Taszár Air Base,Columbus,United States,TZR,LHTA,46.393101,17.917500,531,1,A,Europe/Budapest,airport,OurAirports
6946,11816,Columbus Municipal Airport,Columbus,United States,CLU,KBAK,39.261902,-85.896301,656,NaN,NaN,NaN,airport,OurAirports
6977,11847,Columbus Municipal Airport,Columbus,United States,OLU,KOLU,41.448002,-97.342598,1447,NaN,NaN,NaN,airport,OurAirports

In [15]:
euro_air[euro_air['Altitude']>5000]

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database,Type,Source
1635,1680,Samedan Airport,Samedan,Switzerland,SMV,LSZS,46.534100,9.884110,5600,1,E,Europe/Zurich,airport,OurAirports
1649,1694,Sivas Nuri Demirağ Airport,Sivas,Turkey,VAS,LTAR,39.813801,36.903500,5239,3,E,Europe/Istanbul,airport,OurAirports
1673,1724,Erzurum International Airport,Erzurum,Turkey,ERZ,LTCE,39.956501,41.170200,5763,3,E,Europe/Istanbul,airport,OurAirports
1675,1728,Van Ferit Melen Airport,Van,Turkey,VAN,LTCI,38.468201,43.332298,5480,3,E,Europe/Istanbul,airport,OurAirports
4459,5796,Kars Airport,Kars,Turkey,KSY,LTCF,40.562199,43.115002,5889,3,E,Europe/Istanbul,airport,OurAirports
4462,5799,Ağrı Airport,Agri,Turkey,AJI,LTCO,39.654541,43.025978,5462,3,E,Europe/Istanbul,airport,OurAirports
5049,6479,Courchevel Airport,Courcheval,France,CVF,LFLJ,45.396702,6.634720,6588,1,E,Europe/Paris,airport,OurAirports
5875,8080,Méribel Altiport,Ajaccio,France,MFX,LFKX,45.407003,6.577942,5636,1,U,Europe/Paris,airport,OurAirports

In [16]:
euro_air[euro_air['Altitude']==euro_air['Altitude'].max()]

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database,Type,Source
5049,6479,Courchevel Airport,Courcheval,France,CVF,LFLJ,45.396702,6.63472,6588,1,E,Europe/Paris,airport,OurAirports

In [17]:
airports[airports['City']=='Moscow']

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database,Type,Source
2825,2985,Sheremetyevo International Airport,Moscow,Russia,SVO,UUEE,55.972599,37.414600,622,3,N,Europe/Moscow,airport,OurAirports
2828,2988,Vnukovo International Airport,Moscow,Russia,VKO,UUWW,55.591499,37.261501,685,3,N,Europe/Moscow,airport,OurAirports
3794,4029,Domodedovo International Airport,Moscow,Russia,DME,UUDD,55.408798,37.906300,588,3,N,Europe/Moscow,airport,OurAirports
4065,4360,Bykovo Airport,Moscow,Russia,BKA,UUBB,55.617199,38.060001,427,3,N,Europe/Moscow,airport,OurAirports
6197,8661,Ostafyevo International Airport,Moscow,Russia,NaN,UUMO,55.511700,37.507198,568,3,N,Europe/Moscow,airport,OurAirports
7115,11986,Myachkovo Airport,Moscow,Russia,NaN,UUBM,55.560001,37.985001,410,NaN,NaN,NaN,airport,OurAirports

In [18]:
moskow= airports[(airports['City'] == 'Moscow') & ~(airports['IATA'].isna()) ]

In [19]:
list_msk = ['SVO','VKO','DME','BKA']
airports[airports['IATA'].isin(list_msk)]

,Airport ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz database,Type,Source
2825,2985,Sheremetyevo International Airport,Moscow,Russia,SVO,UUEE,55.972599,37.414600,622,3,N,Europe/Moscow,airport,OurAirports
2828,2988,Vnukovo International Airport,Moscow,Russia,VKO,UUWW,55.591499,37.261501,685,3,N,Europe/Moscow,airport,OurAirports
3794,4029,Domodedovo International Airport,Moscow,Russia,DME,UUDD,55.408798,37.906300,588,3,N,Europe/Moscow,airport,OurAirports
4065,4360,Bykovo Airport,Moscow,Russia,BKA,UUBB,55.617199,38.060001,427,3,N,Europe/Moscow,airport,OurAirports

In [22]:
columns = ['Airline','Airline ID','Source airport','Source airport ID','Destination airport',
            'Destination airport ID','Codeshare','Stops','Equipment']
routes = pd.read_csv('datasets/routes.csv', names = columns)
routes.head()

,Airline,Airline ID,Source airport,Source airport ID,Destination airport,Destination airport ID,Codeshare,Stops,Equipment
0,2B,410,AER,2965,KZN,2990,NaN,0,CR2
1,2B,410,ASF,2966,KZN,2990,NaN,0,CR2
2,2B,410,ASF,2966,MRV,2962,NaN,0,CR2
3,2B,410,CEK,2968,KZN,2990,NaN,0,CR2
4,2B,410,CEK,2968,OVB,4078,NaN,0,CR2

In [23]:
routes[routes['Source airport'].isin(moskow.IATA)]['Source airport'].value_counts()

DME    324
SVO    199
VKO     86
Name: Source airport, dtype: int64